import mongoose from "mongoose";

const themeSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      // e.g., cyber-neon, void-crimson
    },
    name: {
      type: String,
      required: true,
      // Display name
    },
    description: {
      type: String,
      default: "",
    },
    // CSS variable map — persisted so admin can add themes without deploy
    colors: {
      primary: { type: String, required: true },
      primaryContainer: { type: String, required: true },
      secondary: { type: String, required: true },
      secondaryContainer: { type: String, required: true },
      tertiary: { type: String, required: true },
      background: { type: String, required: true },
      surface: { type: String, required: true },
      surfaceContainer: { type: String, required: true },
      surfaceVariant: { type: String, required: true },
      onSurface: { type: String, required: true },
      onSurfaceVariant: { type: String, required: true },
      outline: { type: String, required: true },
      error: { type: String, required: true },
    },
    // optional meta for UI
    preview: {
      gradient: { type: String, default: "" }, // css gradient string
      icon: { type: String, default: "palette" },
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    isDefault: {
      type: Boolean,
      default: false,
    },
    order: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

themeSchema.index({ isActive: 1 });
// key already indexed via unique:true

const Theme = mongoose.model("Theme", themeSchema);
export default Theme;

// Predefined 10 theme definitions (also used for seeding)
export const DEFAULT_THEMES = [
  {
    key: "cyber-neon",
    name: "CYBER_NEON",
    description: "Default neural grid — electric cyan on void black",
    colors: {
      primary: "#8ff5ff",
      primaryContainer: "#00eefc",
      secondary: "#d674ff",
      secondaryContainer: "#9800d0",
      tertiary: "#ff6e81",
      background: "#0e0e0e",
      surface: "#0e0e0e",
      surfaceContainer: "#1a1919",
      surfaceVariant: "#262626",
      onSurface: "#ffffff",
      onSurfaceVariant: "#adaaaa",
      outline: "#777575",
      error: "#ff716c",
    },
    preview: { gradient: "linear-gradient(135deg,#8ff5ff,#d674ff)", icon: "bolt" },
    isDefault: true,
    order: 1,
  },
  {
    key: "void-crimson",
    name: "VOID_CRIMSON",
    description: "Blood protocol — crimson fire on obsidian",
    colors: {
      primary: "#ff3b30",
      primaryContainer: "#ff6b6b",
      secondary: "#ff8a65",
      secondaryContainer: "#bf360c",
      tertiary: "#ffd740",
      background: "#0a0a0a",
      surface: "#141010",
      surfaceContainer: "#1f1a1a",
      surfaceVariant: "#2a2525",
      onSurface: "#ffffff",
      onSurfaceVariant: "#c4b5b5",
      outline: "#8d6e63",
      error: "#ff5252",
    },
    preview: { gradient: "linear-gradient(135deg,#ff3b30,#ff8a65)", icon: "local_fire_department" },
    order: 2,
  },
  {
    key: "synth-purple",
    name: "SYNTH_PURPLE",
    description: "Retro synthwave — neon purple haze",
    colors: {
      primary: "#b388ff",
      primaryContainer: "#7c4dff",
      secondary: "#ff80ab",
      secondaryContainer: "#c2185b",
      tertiary: "#80d8ff",
      background: "#0f0e1a",
      surface: "#0f0e1a",
      surfaceContainer: "#1a1830",
      surfaceVariant: "#2a2850",
      onSurface: "#ffffff",
      onSurfaceVariant: "#b39ddb",
      outline: "#7e57c2",
      error: "#ff8a80",
    },
    preview: { gradient: "linear-gradient(135deg,#7c4dff,#ff80ab)", icon: "auto_awesome" },
    order: 3,
  },
  {
    key: "arctic-frost",
    name: "ARCTIC_FROST",
    description: "Sub-zero optics — ice blue on steel",
    colors: {
      primary: "#82b1ff",
      primaryContainer: "#2979ff",
      secondary: "#84ffff",
      secondaryContainer: "#00b8d4",
      tertiary: "#b9f6ca",
      background: "#0a0f14",
      surface: "#0a0f14",
      surfaceContainer: "#111a22",
      surfaceVariant: "#1e2e3a",
      onSurface: "#e3f2fd",
      onSurfaceVariant: "#90a4ae",
      outline: "#546e7a",
      error: "#ff8a80",
    },
    preview: { gradient: "linear-gradient(135deg,#2979ff,#84ffff)", icon: "ac_unit" },
    order: 4,
  },
  {
    key: "toxic-green",
    name: "TOXIC_GREEN",
    description: "Biohazard — radioactive lime breach",
    colors: {
      primary: "#76ff03",
      primaryContainer: "#64dd17",
      secondary: "#eeff41",
      secondaryContainer: "#aeea00",
      tertiary: "#ff9100",
      background: "#0a0f0a",
      surface: "#0a0f0a",
      surfaceContainer: "#141f14",
      surfaceVariant: "#1e2f1e",
      onSurface: "#e8f5e9",
      onSurfaceVariant: "#a5d6a7",
      outline: "#558b2f",
      error: "#ff6e40",
    },
    preview: { gradient: "linear-gradient(135deg,#76ff03,#eeff41)", icon: "biotech" },
    order: 5,
  },
  {
    key: "solar-flare",
    name: "SOLAR_FLARE",
    description: "Solar incursion — amber fusion",
    colors: {
      primary: "#ffab00",
      primaryContainer: "#ff6d00",
      secondary: "#ffd740",
      secondaryContainer: "#ffab00",
      tertiary: "#ff3d00",
      background: "#0f0a00",
      surface: "#0f0a00",
      surfaceContainer: "#1f1a00",
      surfaceVariant: "#2f2700",
      onSurface: "#fff8e1",
      onSurfaceVariant: "#ffe082",
      outline: "#ff6f00",
      error: "#ff3d00",
    },
    preview: { gradient: "linear-gradient(135deg,#ff6d00,#ffd740)", icon: "wb_sunny" },
    order: 6,
  },
  {
    key: "midnight-abyss",
    name: "MIDNIGHT_ABYSS",
    description: "Deep void — indigo abyss",
    colors: {
      primary: "#536dfe",
      primaryContainer: "#3d5afe",
      secondary: "#7c4dff",
      secondaryContainer: "#651fff",
      tertiary: "#18ffff",
      background: "#050508",
      surface: "#050508",
      surfaceContainer: "#0f0f14",
      surfaceVariant: "#1a1a24",
      onSurface: "#ffffff",
      onSurfaceVariant: "#9fa8da",
      outline: "#3949ab",
      error: "#ff5252",
    },
    preview: { gradient: "linear-gradient(135deg,#3d5afe,#7c4dff)", icon: "dark_mode" },
    order: 7,
  },
  {
    key: "neon-cyber",
    name: "NEON_CYBER",
    description: "Night city — magenta + cyan overload",
    colors: {
      primary: "#ff00ff",
      primaryContainer: "#e040fb",
      secondary: "#00ffff",
      secondaryContainer: "#00e5ff",
      tertiary: "#ffff00",
      background: "#0a0014",
      surface: "#0a0014",
      surfaceContainer: "#1a0033",
      surfaceVariant: "#2a0050",
      onSurface: "#ffffff",
      onSurfaceVariant: "#e1bee7",
      outline: "#aa00ff",
      error: "#ff1744",
    },
    preview: { gradient: "linear-gradient(135deg,#ff00ff,#00ffff)", icon: "nightlife" },
    order: 8,
  },
  {
    key: "blood-protocol",
    name: "BLOOD_PROTOCOL",
    description: "War mode — tactical red & gunmetal",
    colors: {
      primary: "#d32f2f",
      primaryContainer: "#b71c1c",
      secondary: "#ff6e40",
      secondaryContainer: "#dd2c00",
      tertiary: "#ffd600",
      background: "#0d0d0d",
      surface: "#0d0d0d",
      surfaceContainer: "#1a1a1a",
      surfaceVariant: "#2a2a2a",
      onSurface: "#ffffff",
      onSurfaceVariant: "#b0b0b0",
      outline: "#616161",
      error: "#ff1744",
    },
    preview: { gradient: "linear-gradient(135deg,#b71c1c,#ff6e40)", icon: "security" },
    order: 9,
  },
  {
    key: "ghost-white",
    name: "GHOST_WHITE",
    description: "Specter — inverted high-contrast",
    colors: {
      primary: "#00e5ff",
      primaryContainer: "#00b8d4",
      secondary: "#651fff",
      secondaryContainer: "#6200ea",
      tertiary: "#ff4081",
      background: "#f5f5f5",
      surface: "#ffffff",
      surfaceContainer: "#eeeeee",
      surfaceVariant: "#e0e0e0",
      onSurface: "#0e0e0e",
      onSurfaceVariant: "#424242",
      outline: "#9e9e9e",
      error: "#d50000",
    },
    preview: { gradient: "linear-gradient(135deg,#ffffff,#00e5ff)", icon: "light_mode" },
    order: 10,
  },
];
